SELECT DATABASE() AS current_database, VERSION() AS mysql_version;

SELECT TABLE_NAME, ENGINE, TABLE_COLLATION, TABLE_ROWS
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE()
ORDER BY TABLE_NAME;

SELECT TABLE_NAME, CONSTRAINT_NAME, COLUMN_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
FROM information_schema.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = DATABASE()
  AND REFERENCED_TABLE_NAME IS NOT NULL
ORDER BY TABLE_NAME, CONSTRAINT_NAME, ORDINAL_POSITION;

SELECT 'utenti' AS table_name, COUNT(*) AS row_count FROM utenti
UNION ALL
SELECT 'eventi' AS table_name, COUNT(*) AS row_count FROM eventi
UNION ALL
SELECT 'iscrizioni' AS table_name, COUNT(*) AS row_count FROM iscrizioni;
